#!/usr/bin/env php
<?php

$autoload = array(
    __DIR__.'/../../autoload.php',
    __DIR__.'/../vendor/autoload.php',
    __DIR__.'/vendor/autoload.php',
);

foreach ($autoload as $file) {
    if (file_exists($file)) {
        define('BENCHY_AUTOLOAD', $file);
        break;
    }
}
unset($file);

if (!defined('BENCHY_AUTOLOAD')) {
    return 1;
}

require BENCHY_AUTOLOAD;

$command = new \Benchy\BenchmarkCommand();

$application = new \Symfony\Component\Console\Application();
$application->add($command);
$application->setDefaultCommand($command->getName());
$application->run();
