#!/usr/bin/env php
<?php

$autoload = array(
    __DIR__.'/../../vendor/autoload.php',
    __DIR__.'/../vendor/autoload.php',
    __DIR__.'/vendor/autoload.php',
);

foreach ($autoload as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}
unset($file);

$command = new \Benchy\BenchmarkCommand();

$application = new \Symfony\Component\Console\Application();
$application->add($command);
$application->setDefaultCommand($command->getName());
$application->run();
