#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$command = new \Benchy\BenchmarkCommand();

$application = new Application();
$application->add($command);
$application->setDefaultCommand($command->getName());
$application->run();